### ISSUE TITLE
[Question] Do you mind to share the Bash prompt?

### ISSUE THREAD

**Issue by dirsigler** [arcticicestudio/nord-terminator#8]
Hey guys!
Thanks for the cool tools, I love using the nord tools (vim, terminator) at my workstation.
I really love the first picture with the 2 level bash prompt. Do you mind to share the configuration for this?

With best regards

**Comment by arcticicestudio** [comment]
Sure, it is available in the [dotfile repository][prompt]. Make sure to source the [official `git-prompt.sh` script][git-prompt] like [this][git-comp], otherwise the prompt will cause two error messages to be printed in the terminal each time a command gets executed (caused by the missing `__git_ps1` variable).

The prompt is not finished yet, there are plans to add features like SSH detection and safer `git` directory support detection. Maybe check out the repository/file for changes from time to time or add the repository to your watchlist to get notified about changes.

[prompt]: https://github.com/arcticicestudio/igloo/blob/develop/snowblocks/bash/core/prompt
[git-comp]: https://github.com/arcticicestudio/igloo/blob/develop/snowblocks/bash/bootstrap#L128
[git-prompt]: https://github.com/git/git/blob/master/contrib/completion/git-prompt.sh
